services:
  - type: web
    name: parch-site-insti      # Change to your app's name
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
