services:
  - type: web
    name: parch-site-insti         # Change this to your app name
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 18
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
